version: '3.8'

services:
  sch-auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sch-auth-container
    environment:
      DB_URL: jdbc:postgresql://schedule_university_DB:5432/schedule_university_auth
      DB_USER: abuser
      DB_PASSWORD: abuser
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
    ports:
      - "8083:8082"
    networks:
      - schedule_network

networks:
  schedule_network:
    external: true