spring:
  application:
    name: Schedule Auth
    systemName: tchs
    version: 0.0.1-SNAPSHOT
  profiles:
    active: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/schedule_university_auth}
    username: ${DB_USER:abuser}
    password: ${DB_PASSWORD:abuser}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  liquibase:
    enabled: false

server:
  port: 8082

logging:
  config: classpath:log4j2-prod.xml

jwt:
  secret: aojisfoapwjfeqauiwfpqwfjipqfqpiwfjopqowfjiqpowfjiqjpqowjfpqwejfipqwefjpqwfjeqw
  parser-secret: verysecurekey123456789
  main-secret: aojisfoapwjfeqauiwfpqwfjipqfqpiwfjopqowfjiqpowfjiqjpqowjfpqwejfipqwefjpqwfjeqw
  auth-issuer: sch-auth
  main-audience: sch-main
  access-token-expiration: 900 # 15 minutes
  refresh-token-expiration: 3600 # 1 hour