spring:
  application:
    name: Schedule Auth
    systemName: tchs
    version: 0.0.1-SNAPSHOT
  profiles:
    active: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/schedule_university_auth}
    username: ${DB_USER:abuser}
    password: ${DB_PASSWORD:abuser}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  liquibase:
    enabled: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
    display-request-duration: true
    disable-swagger-default-url: false

server:
  port: 8082

logging:
  config: classpath:log4j2-prod.xml

jwt:
  secret: aojisfoapwjfeqauiwfpqwfjipqfqpiwfjopqowfjiqpowfjiqjpqowjfpqwejfipqwefjpqwfjeqw
  access-token-expiration: 3600
  refresh-token-expiration: 7200