spring:
  application:
    name: Schedule Auth
    systemName: tchs
    version: 0.0.1-SNAPSHOT
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/schedule_university_auth}
    username: ${DB_USER:abuser}
    password: ${DB_PASSWORD:abuser}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  liquibase:
    enabled: true

server:
  port: 8082

logging:
  config: classpath:log4j2-dev.xml
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    liquibase: DEBUG

jwt:
  secret: aojisfoapwjfeqauiwfpqwfjipqfqpiwfjopqowfjiqpowfjiqjpqowjfpqwejfipqwefjpqwfjeqw
  parser-secret: verysecurekey123456789
  main-secret: aojisfoapwjfeqauiwfpqwfjipqfqpiwfjopqowfjiqpowfjiqjpqowjfpqwejfipqwefjpqwfjeqw
  auth-issuer: sch-auth
  main-audience: sch-main
  access-token-expiration: 900 # 15 minutes
  refresh-token-expiration: 3600 # 1 hour