spring:
  application:
    name: Schedule Auth
    systemName: tchs
    version: 0.0.1-SNAPSHOT
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/schedule_university_auth}
    username: ${DB_USER:abuser}
    password: ${DB_PASSWORD:abuser}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  liquibase:
    enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
    display-request-duration: true
    disable-swagger-default-url: false

server:
  port: 8082


logging:
  config: classpath:log4j2-dev.xml
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    liquibase: DEBUG

jwt:
  secret: aojisfoapwjfeqauiwfpqwfjipqfqpiwfjopqowfjiqpowfjiqjpqowjfpqwejfipqwefjpqwfjeqw
  access-token-expiration: 3600
  refresh-token-expiration: 7200